<a href="https://colab.research.google.com/github/sftSalman/tensoflowMaster/blob/main/Custom_loss_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Dense , Input
from tensorflow.keras.losses import Loss
import numpy as np
print("Version of tensorflow is : ",tf.__version__)

Version of tensorflow is :  2.8.2


In [3]:
xs = np.arange(-5,5,1).astype('float32')
ys = xs * 2 - 1

In [4]:
def huber_loss(y_true, y_pred):
  thresold = 1
  error = y_true-y_pred
  return_type = tf.abs(error)<=thresold
  r1 = 0.5* tf.square(error)
  r2 =  thresold * (tf.abs(error) - (0.5*thresold))
  return tf.where(return_type, r1 , r2 )

In [5]:
input = Input(shape=(1,), name ='input_layer')
output_layer = Dense(1,name = 'output_layer')(input)
model_huber_loss = tf.keras.models.Model(inputs = input, outputs = output_layer)

In [ ]:
model_huber_loss.compile(optimizer=tf.keras.optimizers.SGD(),loss= huber_loss)
model_huber_loss.fit(xs,ys,epochs=500,verbose=2)

In [8]:
model_huber_loss.predict([[10.0]])

array([[19.014387]], dtype=float32)

In [9]:
def huber_loss_wrapper(thresold):
    def huber_loss(y_true , y_pred):
        error = y_true - y_pred
        return_type = tf.abs(error) <= thresold
        r1 = 0.5 * tf.square(error)
        r2 = thresold * (tf.abs(error) - (0.5*thresold))
        return tf.where(return_type , r1 , r2)
    return huber_loss

In [10]:
input = Input(shape=(1,) , name="input_layer")
output_layer = Dense(1 , name="output_layer")(input)
model_huber_loss_wrapper = tf.keras.models.Model(inputs=input , outputs=output_layer)
model_huber_loss_wrapper.compile(optimizer="sgd" , loss=huber_loss_wrapper(thresold=1))
model_huber_loss_wrapper.fit(xs,ys,epochs=500,verbose=0)
model_huber_loss_wrapper.predict([[10.0]])

array([[19.030094]], dtype=float32)

In [11]:
class Huber(Loss):
  thresold = 1
  def __init__(self, thresold):
    super().__init__()
    self.thresold = thresold

  def call (self, y_true, y_pred):
    error = y_true - y_pred
    return_type = tf.abs(error) <= self.thresold
    r1 = 0.5 * tf.square(error)
    r2 = self.thresold * (tf.abs(error) - (0.5*self.thresold))
    return tf.where(return_type , r1 , r2)

In [14]:
input = Input(shape=(1,) , name="input_layer")
output_layer = Dense(1 , name="output_layer")(input)
model_huber_loss_class = tf.keras.models.Model(inputs=input , outputs=output_layer)
model_huber_loss_class.compile(optimizer="sgd" , loss=Huber(thresold=2))
model_huber_loss_class.fit(xs,ys,epochs=500,verbose=2)
model_huber_loss_class.predict([[10.0]])

Epoch 1/500
1/1 - 0s - loss: 6.3999 - 265ms/epoch - 265ms/step
Epoch 2/500
1/1 - 0s - loss: 6.1621 - 8ms/epoch - 8ms/step
Epoch 3/500
1/1 - 0s - loss: 5.9249 - 4ms/epoch - 4ms/step
Epoch 4/500
1/1 - 0s - loss: 5.6892 - 4ms/epoch - 4ms/step
Epoch 5/500
1/1 - 0s - loss: 5.4556 - 5ms/epoch - 5ms/step
Epoch 6/500
1/1 - 0s - loss: 5.2240 - 5ms/epoch - 5ms/step
Epoch 7/500
1/1 - 0s - loss: 4.9944 - 5ms/epoch - 5ms/step
Epoch 8/500
1/1 - 0s - loss: 4.7669 - 4ms/epoch - 4ms/step
Epoch 9/500
1/1 - 0s - loss: 4.5413 - 15ms/epoch - 15ms/step
Epoch 10/500
1/1 - 0s - loss: 4.3176 - 7ms/epoch - 7ms/step
Epoch 11/500
1/1 - 0s - loss: 4.0959 - 5ms/epoch - 5ms/step
Epoch 12/500
1/1 - 0s - loss: 3.8760 - 6ms/epoch - 6ms/step
Epoch 13/500
1/1 - 0s - loss: 3.6583 - 12ms/epoch - 12ms/step
Epoch 14/500
1/1 - 0s - loss: 3.4432 - 8ms/epoch - 8ms/step
Epoch 15/500
1/1 - 0s - loss: 3.2331 - 8ms/epoch - 8ms/step
Epoch 16/500
1/1 - 0s - loss: 3.0286 - 8ms/epoch - 8ms/step
Epoch 17/500
1/1 - 0s - loss: 2.8295 - 7m

array([[19.013494]], dtype=float32)